server:
  port: 8080
  max-http-header-size: 100000
  servlet:
    session:
      timeout: 600
spring:
  datasource:
    # 主库配置（写库）
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root12345
      jdbc-url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      type: com.alibaba.druid.pool.DruidDataSource

    # 从库配置（读库）
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root12345
      jdbc-url: jdbc:mysql://localhost:3306/slave?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      type: com.alibaba.druid.pool.DruidDataSource

